apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: maps10-pr
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: maps10
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
