apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: maps10
spec:
  params:
  - name: GIT_REPO
    value: $(body.repository.url)
  - name: APP_NAME 
    value: $(body.repository.name)
  - name: GIT_REVISION 
    value: $(body.head_commit.id)
