apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: maps10
spec:
  params:
  - name: GIT_REPO
    description: Url of the git repository
  - name: GIT_REVISION 
    description: Revision to be used from repo of the code for deployment
  - name: APP_NAME 
    description: The name of the deployment to be created / patched
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: maps10-$(tt.params.APP_NAME)-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: maps10
      params:
      - name: APP_NAME
        value: $(tt.params.APP_NAME) 
      - name: GIT_REPO_URL 
        value: $(tt.params.GIT_REPO)
      - name: GIT_REVISION 
        value: $(tt.params.GIT_REVISION)
      - name: IMAGE_NAME
        value: image-registry.openshift-image-registry.svc:5000/maps10/maps10
      - name: PATH_CONTEXT
        value: .
      - name: VERSION
        value: 14-ubi7
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Mi
