apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: maps10
spec:
  params:
  - name: GIT_REPO
    description: Url of the git repository
  - name: GIT_REVISION 
    description: Revision to be used from repo of the code for deployment
  - name: APP_NAME 
    description: The name of the deployment to be created / patched
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: maps10-$(tt.params.APP_NAME)-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: maps10
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Mi
